disabled_rules:
  - identifier_name
opt_in_rules:
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - indentation_width
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition
indentation_width:
  include_comments: false
line_length:
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true
excluded:
  - Sources/Tests
  - Sources/LinuxMain.swift
cyclomatic_complexity:
  ignores_case_statements: true
indentation: tabs
