#if !canImport(ObjectiveC)
import XCTest

extension Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Tests = [
        ("testMissingFile", testMissingFile),
        ("testOPML2", testOPML2),
        ("testOPMLNested", testOPMLNested),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Tests.__allTests__Tests),
    ]
}
#endif
